# Secret key for JWT
secret_key: 124sajajfgSAf12astASt21y61243sdg21y210wqt12DGBDBDBskdcaa1y12DDASlLJO 


# DB user
DB_USER: postgres

# DB name
DB_NAME: postgres   

# DB password
DB_PASSWORD: postgres


# Command to run the app: 
# uvicorn socnet.main:app --reload
